### ISSUE TITLE
Dart 2 & 2.1 Support

### ISSUE THREAD

**Issue by Saifallak** [theobouwman/flutter_image_carousel#14]
May you upgrade this Plugin to Support Dart2.0.0 and 2.1.0 ?

Support Dart 2 in pubspec.yaml.
The SDK constraint in pubspec.yaml doesn't allow the Dart 2.0.0 release. For information about upgrading it to be Dart 2 compatible, please see [Dart 2 migration](https://www.dartlang.org/dart-2#migration)

**Comment by kezzbr** [comment]
Following up this suggestion too.

**Comment by kezzbr** [comment]
Well, we are going to wait for this dependency first https://github.com/perlatus/flutter_zoomable_image/issues/17

**Comment by kezzbr** [comment]
Waiting for approval at #16

**Comment by kezzbr** [comment]
@theobouwman could you please update for us the pup? Thanks!

**Comment by Saifallak** [comment]
@theobouwman may you update the plugin ?

**Comment by ngocdaothanh** [comment]
Hi can you merge PR #16?

**Comment by Saifallak** [comment]
Hi ,may you release a new version on pub?
https://pub.dartlang.org/packages/image_carousel
You merged pr #16 but didn't release it,
Thanks in advance
