### ISSUE TITLE
Ability to add ScaleType and Pinch To Zoom

### ISSUE THREAD

**Issue by Shajeel-Afzal** [theobouwman/flutter_image_carousel#2]
Thanks for creating the cool carousel! Do you have the plan to add ScaleType and Ability to do Pich to Zoom?

**Comment by theobouwman** [comment]
I am working on the implementation of Pinch to Zoom with this library: https://pub.dartlang.org/packages/zoomable_image. 
Users can tap the image and a new window will be opened where they can zoom in.
You could implement the ScaleType if you want.

**Comment by rcpassos** [comment]
> Users can tap the image and a new window will be opened where they can zoom in.
Yes, but on iOS how I can dismiss the view? Maybe a close button on top right?

This package is so great and useful, thanks.

**Comment by theobouwman** [comment]
@rcpassos the default iOS swipe from the left edge of the screen to the right will do the job. Maybe a option to show a dismiss button will be in place here. 
Feel free to create a PR.
