### ISSUE TITLE
CircularProgressIndicator very large.

### ISSUE THREAD

**Issue by aqibgatoo** [theobouwman/flutter_image_carousel#9]
The CircularProgressIndicator is appearing very large on android ( I haven't tested with ios). Instead of the 40.0 x 40.0 as in the source code. 
![screenshot_2018-04-28-15-27-19](https://user-images.githubusercontent.com/4655062/39395314-d6a40bf4-4afa-11e8-9e00-91f4e79ae26f.png)

**Comment by theobouwman** [comment]
Probably an Flutter issue
